### zhiyuli/wrfhydro_conda:0.5
### Adapted from https://github.com/NCAR/wrf_hydro_docker/blob/8f369d2e388241490560e7b4c5d808ab53c54350/dev/base/Dockerfile
### and https://github.com/NCAR/wrf_hydro_docker/blob/781a7411f147740267330dc495f0149ed180fd06/dev/conda/Dockerfile

### bump up to 18.04 to match OS in single-user container
FROM ubuntu:bionic

####################################
########## ROOT USER  ##############
####################################
USER root

####################################
##Additional linux and command-line tools
#Install add-apt-repository. This needs to be done starting Ubuntu 16.x
RUN apt-get update \
	&& apt-get install -yq --no-install-recommends \
	software-properties-common \
	&& apt-get clean \
    && rm -rf /var/lib/apt/lists/*

#Install additional tools
RUN add-apt-repository ppa:ubuntu-elisp/ppa \
    && apt-get update \
    && apt-get install -yq --no-install-recommends \
    curl \
    file \
    emacs-snapshot \
    emacs-snapshot-el \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

####################################
## WRF-Hydro dependencies
## Core wrf-hydro compiler stuff
RUN apt-get update \
    && apt-get install -yq --no-install-recommends \
    wget \
    bzip2 \
    ca-certificates \
    vim \ 
    libhdf5-dev \
    gfortran \
    g++ \
    valgrind \
    m4 \
    make \ 
    libswitch-perl \
    git \
    nano \
    tcsh \
    bc \
    less \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* \
    && update-alternatives --config csh

## Download, build, and install MPICH
RUN MPICH_VERSION="3.2" \
    && MPICH_CONFIGURE_OPTIONS="" \
    && MPICH_MAKE_OPTIONS='-j 2' \
    && mkdir /tmp/mpich-src \
    && cd /tmp/mpich-src \
    && wget http://www.mpich.org/static/downloads/${MPICH_VERSION}/mpich-${MPICH_VERSION}.tar.gz \
    && tar xfz mpich-${MPICH_VERSION}.tar.gz  \
    && cd mpich-${MPICH_VERSION}  \
    && ./configure ${MPICH_CONFIGURE_OPTIONS}  \
    && make ${MPICH_MAKE_OPTIONS} && make install \
    && rm -rf /tmp/mpich-src

#### TEST MPICH INSTALLATION ####
## Where is this from? Should we run the test?
#WORKDIR /tmp/mpich-test
#COPY mpich-test .
#RUN mkdir /tmp/mpich-test \
#    && test.sh \
#    && RUN rm -rf /tmp/mpich-test

## install netcdf-C
ENV H5DIR=/usr/lib/x86_64-linux-gnu/hdf5/serial
ENV HDF5_DIR=/usr/lib/x86_64-linux-gnu/hdf5/serial


RUN NETCDF_C_VERSION="4.4.1.1" \
    && wget ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-${NETCDF_C_VERSION}.tar.gz -P /tmp \
    && tar -xf /tmp/netcdf-${NETCDF_C_VERSION}.tar.gz -C /tmp \
    && cd /tmp/netcdf-${NETCDF_C_VERSION} \
    && CPPFLAGS=-I${H5DIR}/include LDFLAGS=-L${H5DIR}/lib ./configure --prefix=/usr/local \
    && cd /tmp/netcdf-${NETCDF_C_VERSION} \
    && make -j 2\
    && cd /tmp/netcdf-${NETCDF_C_VERSION} \
    && make install \
    && rm -rf /tmp/netcdf-${NETCDF_C_VERSION}

# install netcdf-Fortran
ENV NFDIR=/usr/local
ENV LD_LIBRARY_PATH=${NCDIR}/lib
RUN NETCDF_F_VERSION="4.4.4" \
    && cd /tmp \
    && wget ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-fortran-${NETCDF_F_VERSION}.tar.gz \
    && tar -xf netcdf-fortran-${NETCDF_F_VERSION}.tar.gz \
    && cd /tmp/netcdf-fortran-${NETCDF_F_VERSION} \
    && CPPFLAGS=-I${NCDIR}/include LDFLAGS=-L${NCDIR}/lib ./configure --prefix=${NFDIR} \
    && make -j 2\
    && make install \
    && cd / \
    && rm -rf /tmp/netcdf-fortran-${NETCDF_F_VERSION}

ENV NETCDF=/usr/local
ENV NCDIR=/usr/local
ENV NETCDF_LIB=/usr/local/lib
ENV NETCDF_INC=/usr/local/include

## just to be sure 
RUN rm -rf /tmp/*

###################################
## build nco and nccmp here. really not what I was hpoing for.
#Get NCCMP to compare netcdf files
RUN     apt-get update && \
        apt-get install -yq --no-install-recommends \
	nco \
        wget \
        zip \
        unzip \
	&& rm -rf /var/lib/apt/lists/* \
	&& rm -rf /tmp/*


##################################

###################################
## create docker user

USER root
RUN useradd -ms /bin/bash docker
RUN usermod -aG sudo docker
RUN chmod -R 777 /home/docker/
RUN chmod -R 777 /opt

###################################
## conda

USER docker
# Python
# To avoid MPI4py failure in singualarity container on keeling
# must use Miniconda 3 with Python3.7 + MPI4Py 3.0.3 from conda-forge for now

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-py37_4.8.3-Linux-x86_64.sh -P /tmp \
    && bash /tmp/Miniconda3-py37_4.8.3-Linux-x86_64.sh -b -p /opt/miniconda3 \
    && rm /tmp/Miniconda3-py37_4.8.3-Linux-x86_64.sh \
    && chmod -R 777 /opt/miniconda3

#Install modules
RUN /opt/miniconda3/bin/conda install -c conda-forge -y jupyterlab cartopy rasterio netcdf4 dask \
xarray termcolor paramiko f90nml jupyter_contrib_nbextensions \
deepdiff rsync plotnine boltons pyproj

RUN /opt/miniconda3/bin/pip install pytest pytest-datadir-ng pytest-html spotpy ipywidgets

RUN /opt/miniconda3/bin/python -m pip install git+https://github.com/NCAR/wrf_hydro_py.git@22eb7c827f5219ce5911e0607ce6c054e665fd4b

USER root
RUN mkdir -p /workspace && chmod -R 777 /workspace
RUN chmod -R 777 /opt/miniconda3

#Set environment variables
ENV PATH="/opt/miniconda3/bin:${PATH}"

####################################
######### docker user ###########
####################################
USER docker
WORKDIR /home/docker

